<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Print Vouchers - {{ $router ? $router->name : 'All Routers' }}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @media print {
            body { margin: 0; }
            .no-print { display: none !important; }
            .voucher-card { 
                break-inside: avoid; 
                page-break-inside: avoid;
                margin-bottom: 10px;
            }
        }
        .voucher-card {
            border: 2px dashed #ccc;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        }
    </style>
</head>
<body class="bg-gray-100 p-4">
    <!-- Print Controls -->
    <div class="no-print mb-6 bg-white p-4 rounded-lg shadow-md">
        <div class="flex justify-between items-center">
            <h1 class="text-2xl font-bold text-gray-800">
                Print Vouchers - {{ $router ? $router->name : 'All Routers' }}
            </h1>
            <div class="flex gap-2">
                <button onclick="window.print()" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition">
                    🖨️ Print
                </button>
                <a href="{{ route('vouchers.index') }}{{ $router ? '?router=' . $router->id : '' }}" class="bg-gray-600 text-white px-4 py-2 rounded-lg hover:bg-gray-700 transition">
                    ← Back
                </a>
            </div>
        </div>
        <p class="text-gray-600 mt-2">
            Showing {{ $vouchers->count() }} {{ $status }} vouchers
            @if($router) for {{ $router->name }} @endif
        </p>
    </div>

    <!-- Voucher Grid -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        @forelse($vouchers as $voucher)
            <div class="voucher-card p-4 rounded-lg text-white shadow-lg">
                <div class="text-center">
                    <!-- Header -->
                    <div class="border-b border-white/30 pb-2 mb-3">
                        <h3 class="text-lg font-bold">WiFi Voucher</h3>
                        <p class="text-sm opacity-90">{{ $voucher->router->name }}</p>
                    </div>
                    
                    <!-- Voucher Code -->
                    <div class="bg-white/20 rounded-lg p-3 mb-3">
                        <p class="text-xs opacity-90 mb-1">Username & Password</p>
                        <p class="text-2xl font-bold font-mono tracking-wider">{{ $voucher->code }}</p>
                    </div>
                    
                    <!-- Profile Info -->
                    <div class="text-sm space-y-1 mb-3">
                        <p><span class="opacity-75">Plan:</span> <strong>{{ $voucher->profile }}</strong></p>
                        <p><span class="opacity-75">Status:</span> 
                            <span class="px-2 py-1 rounded text-xs {{ $voucher->is_used ? 'bg-red-500' : 'bg-green-500' }}">
                                {{ $voucher->is_used ? 'USED' : 'ACTIVE' }}
                            </span>
                        </p>
                    </div>
                    
                    <!-- Instructions -->
                    <div class="border-t border-white/30 pt-2 text-xs opacity-75">
                        <p>1. Connect to WiFi</p>
                        <p>2. Enter this code</p>
                        <p>3. Enjoy internet!</p>
                    </div>
                    
                    <!-- Footer -->
                    <div class="mt-3 text-xs opacity-60">
                        <p>Created: {{ $voucher->created_at->format('M d, Y') }}</p>
                        @if($voucher->is_used && $voucher->used_at)
                            <p>Used: {{ $voucher->used_at->format('M d, Y H:i') }}</p>
                        @endif
                    </div>
                </div>
            </div>
        @empty
            <div class="col-span-full text-center py-12">
                <p class="text-gray-500 text-lg">No vouchers found to print</p>
                <a href="{{ route('vouchers.create') }}{{ $router ? '?router=' . $router->id : '' }}" class="no-print inline-block mt-4 bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700 transition">
                    Create Vouchers
                </a>
            </div>
        @endforelse
    </div>

    <!-- Print Footer -->
    <div class="no-print mt-8 text-center text-gray-500">
        <p>Generated by Passtik on {{ now()->format('F j, Y \a\t g:i A') }}</p>
    </div>

    <script>
        // Auto-focus print dialog when page loads
        window.addEventListener('load', function() {
            // Small delay to ensure page is fully rendered
            setTimeout(() => {
                if (window.location.search.includes('auto_print=1')) {
                    window.print();
                }
            }, 500);
        });
    </script>
</body>
</html>